export const cities = [
    "San Francisco, USA",
    "New York, USA",
    "London, UK",
    "Berlin, Germany",
    "Paris, France",
    "Tokyo, Japan",
    "Singapore, Singapore",
    "Bangalore, India",
    "Sydney, Australia",
    "Toronto, Canada",
    "Mumbai, India",
    "Amsterdam, Netherlands",
    "Seoul, South Korea",
    "Tel Aviv, Israel",
    "Austin, USA",
    "Seattle, USA",
    "Stockholm, Sweden",
    "Dublin, Ireland",
    "Zurich, Switzerland",
    "Singapore",
    "Hong Kong",
    "Dubai, UAE",
    "Barcelona, Spain",
    "Madrid, Spain",
    "Munich, Germany",
    "Bangkok, Thailand",
    "Ho Chi Minh City, Vietnam",
    "Jakarta, Indonesia",
    "New Delhi, India",
    "Chennai, India",
    "Hyderabad, India",
    "Pune, India",
    "Ahmedabad, India",
    "Remote"
];