export const skills = [
    "React",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "Node.js",
    "Python",
    "Java",
    "C++",
    "C#",
    "Go",
    "Rust",
    "Swift",
    "Kotlin",
    "PHP",
    "Ruby",
    "SQL",
    "NoSQL",
    "MongoDB",
    "PostgreSQL",
    "Firebase",
    "AWS",
    "Azure",
    "Google Cloud",
    "Docker",
    "Kubernetes",
    "GraphQL",
    "REST API",
    "Tailwind CSS",
    "Material UI",
    "Redux",
    "Zustand",
    "React Native",
    "Flutter",
    "Dart",
    "Vue.js",
    "Angular",
    "Svelte",
    "SolidJS",
    "Qwik",
    "Remix",
    "RedwoodJS",
    "Astro",
    "Eleventy",
    "Alpine.js",
    "Preact",
    "Lit",
    "Ember.js",
    "Backbone.js",
    "Unity",
    "Unreal Engine",
    "Machine Learning",
    "Deep Learning",
    "AI",
    "Data Science",
    "Cloud Computing",
    "Cybersecurity",
    "DevOps",
    "CI/CD",
    "Blockchain",
    "Web3",
    "Figma",
    "UI/UX Design",
    "Git",
    "GitHub",
    "Agile",
    "Scrum",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Hugging Face",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "Django",
    "Flask",
    "FastAPI",
    "Spring Boot",
    "ASP.NET Core",
    "Laravel",
    "Symfony",
    "CodeIgniter",
    "CakePHP",
    "Ruby on Rails",
    "Phoenix Framework",
    "Express.js",
    "NestJS",
    "Fastify",
    "Koa.js",
    "Hapi.js",
    "AdonisJS",
    "Socket.io",
    "Elasticsearch",
    "Redis",
    "Terraform",
    "Ansible",
    "Prometheus",
    "Grafana",
    "RabbitMQ",
    "Kafka",
    "Apache Spark",
    "Hadoop",
    "Tableau",
    "Power BI",
    "Solidity",
    "Ethereum",
    "Smart Contracts",
    "Penetration Testing",
    "Ethical Hacking",
    "ISO 27001",
    "Linux",
    "Ubuntu",
    "CentOS",
    "Nginx",
    "Apache",
    "Vite",
    "Webpack",
    "Babel",
    "Jest",
    "Vitest",
    "Cypress",
    "Playwright",
    "Selenium",
    "Storybook",
    "Prisma",
    "TypeORM",
    "Sequelize",
    "Mongoose",
    "Apollo Client",
    "SWR",
    "TanStack Query",
    "Chakra UI",
    "Ant Design",
    "Shadcn UI",
    "Radix UI",
    "Headless UI",
    "PrimeReact",
    "Bootstrap",
    "Bulma",
    "Foundation CSS",
    "Framer Motion",
    "Three.js",
    "D3.js",
    "GSAP",
    "Electron",
    "Tauri",
    "Ionic",
    "Capacitor",
    "WordPress",
    "Shopify",
    "Strapi",
    "Ghost CMS",
    "Contentful",
    "Digital Ocean",
    "Heroku",
    "Netlify",
    "Vercel",
    "Cloudflare",
    "Supabase",
    "Auth0",
    "Clerk",
    "OAuth",
    "JWT",
    "Microservices",
    "Serverless",
    "TDD",
    "BDD",
    "OpenAPI",
    "Swagger",
    "Postman",
    "Jira",
    "Trello",
    "Asana",
    "Slack API",
    "Stripe API",
    "OpenAI API",
    "LangChain",
    "LlamaIndex",
    "Vector Databases",
    "Pinecone",
    "Milvus",
    "ChromaDB",
    "Weaviate"
];